# Generated by Django 4.2.30 on 2026-05-12 12:41

import blockchain.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_number", models.BigIntegerField(unique=True)),
                ("previous_hash", models.CharField(max_length=64)),
                ("merkle_root", models.CharField(max_length=64)),
                ("rollup_proof", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("nonce", models.BigIntegerField()),
                ("hash", models.CharField(max_length=64, unique=True)),
                ("transaction_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "blocks",
                "ordering": ["-block_number"],
            },
        ),
        migrations.CreateModel(
            name="BlockchainNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("network_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("chain_id", models.IntegerField()),
                ("rpc_url", models.URLField()),
                ("consensus_type", models.CharField(default="PBFT", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "blockchain_networks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ValidatorNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=64, unique=True)),
                ("public_key", models.TextField()),
                (
                    "stake_amount",
                    models.DecimalField(decimal_places=18, default=0, max_digits=30),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blockchain.blockchainnetwork",
                    ),
                ),
            ],
            options={
                "db_table": "validator_nodes",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_hash", models.CharField(max_length=64, unique=True)),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Record Creation"),
                            ("UPDATE", "Record Update"),
                            ("SHARE", "Record Sharing"),
                            ("VERIFY", "Record Verification"),
                            ("ACCESS", "Access Request"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sender", models.CharField(max_length=200)),
                ("receiver", models.CharField(blank=True, max_length=200, null=True)),
                ("data_hash", models.CharField(max_length=64)),
                ("signature", models.TextField()),
                (
                    "nonce",
                    models.CharField(
                        default=blockchain.models.generate_uuid, max_length=64
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("gas_used", models.BigIntegerField(default=0)),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blockchain.block",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SmartContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_address", models.CharField(max_length=200, unique=True)),
                ("contract_type", models.CharField(max_length=100)),
                ("abi", models.JSONField()),
                ("bytecode", models.TextField()),
                ("deployed_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blockchain.blockchainnetwork",
                    ),
                ),
            ],
            options={
                "db_table": "smart_contracts",
            },
        ),
        migrations.CreateModel(
            name="RollupBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.CharField(max_length=64, unique=True)),
                ("merkle_root", models.CharField(max_length=64)),
                ("zk_proof", models.TextField()),
                ("proof_type", models.CharField(default="zk_snark", max_length=20)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blockchain.blockchainnetwork",
                    ),
                ),
                ("transactions", models.ManyToManyField(to="blockchain.transaction")),
            ],
            options={
                "db_table": "rollup_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrossChainMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=64, unique=True)),
                ("data_hash", models.CharField(max_length=64)),
                ("proof", models.TextField()),
                ("signature", models.TextField()),
                ("nonce", models.CharField(max_length=64)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("relayed_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_messages",
                        to="blockchain.blockchainnetwork",
                    ),
                ),
                (
                    "target_chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_messages",
                        to="blockchain.blockchainnetwork",
                    ),
                ),
            ],
            options={
                "db_table": "cross_chain_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="block",
            name="network",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="blockchain.blockchainnetwork",
            ),
        ),
    ]
