# Generated by Django 4.2.30 on 2026-05-14 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("secret_key", models.CharField(blank=True, max_length=32)),
                (
                    "backup_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of one-time backup codes (hashed)",
                    ),
                ),
                ("last_verified", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_auth",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Two-Factor Authentication",
                "verbose_name_plural": "Two-Factor Authentications",
                "db_table": "accounts_two_factor_auth",
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "username",
                    models.CharField(blank=True, db_index=True, max_length=150),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("successful", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "accounts_login_attempts",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="accounts_lo_ip_addr_27dc55_idx",
                    ),
                    models.Index(
                        fields=["username", "timestamp"],
                        name="accounts_lo_usernam_10f7a0_idx",
                    ),
                ],
            },
        ),
    ]
