# Generated by Django 4.2.30 on 2026-05-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_twofactorauth_loginattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "User Login"),
                    ("LOGOUT", "User Logout"),
                    ("LOGIN_FAILED", "Failed Login Attempt"),
                    ("PASSWORD_CHANGE", "Password Changed"),
                    ("TOKEN_REFRESH", "Token Refreshed"),
                    ("LOGIN_2FA_PENDING", "2FA Verification Pending"),
                    ("LOGIN_2FA", "2FA Login Verified"),
                ],
                max_length=20,
            ),
        ),
    ]
