# Generated by Django 4.2.30 on 2026-05-14 00:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blockchain", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hospital_id",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("license_number", models.CharField(max_length=100)),
                ("public_key", models.TextField()),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blockchain_network",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blockchain.blockchainnetwork",
                    ),
                ),
            ],
            options={
                "db_table": "hospitals",
            },
        ),
        migrations.CreateModel(
            name="InsuranceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("license_number", models.CharField(max_length=100)),
                ("public_key", models.TextField()),
            ],
            options={
                "db_table": "insurance_providers",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=64, unique=True)),
                ("public_key", models.TextField()),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("blood_type", models.CharField(blank=True, max_length=10)),
                ("allergies", models.TextField(blank=True)),
                ("emergency_contact", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "patients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.CharField(max_length=64, unique=True)),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("DIAGNOSIS", "Diagnosis"),
                            ("LAB_RESULT", "Laboratory Result"),
                            ("PRESCRIPTION", "Prescription"),
                            ("IMAGING", "Medical Imaging"),
                            ("SURGERY", "Surgery Report"),
                            ("DISCHARGE", "Discharge Summary"),
                            ("INSURANCE", "Insurance Claim"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("ipfs_hash", models.CharField(blank=True, max_length=64)),
                ("file_size", models.BigIntegerField(default=0)),
                ("encryption_key_hash", models.CharField(blank=True, max_length=64)),
                ("data_hash", models.CharField(max_length=64)),
                ("metadata_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "blockchain_tx",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blockchain.transaction",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthcare.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthcare.patient",
                    ),
                ),
            ],
            options={
                "db_table": "medical_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lab_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("accreditation", models.CharField(max_length=100)),
                ("public_key", models.TextField()),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthcare.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "laboratories",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_id", models.CharField(max_length=255, unique=True)),
                ("actor", models.CharField(max_length=200)),
                ("actor_type", models.CharField(max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Record Created"),
                            ("READ", "Record Accessed"),
                            ("UPDATE", "Record Updated"),
                            ("SHARE", "Record Shared"),
                            ("DELETE", "Record Deleted"),
                            ("ACCESS_DENIED", "Access Denied"),
                        ],
                        max_length=15,
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthcare.medicalrecord",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AccessPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permission_id", models.CharField(max_length=64, unique=True)),
                ("grantee", models.CharField(max_length=200)),
                (
                    "grantee_type",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "Hospital"),
                            ("LAB", "Laboratory"),
                            ("INSURANCE", "Insurance"),
                            ("DOCTOR", "Doctor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("READ", "Read Only"),
                            ("WRITE", "Read and Write"),
                            ("SHARE", "Share with Others"),
                        ],
                        max_length=10,
                    ),
                ),
                ("purpose", models.TextField()),
                ("signature", models.TextField()),
                ("zk_proof", models.TextField(blank=True)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grantor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="granted_permissions",
                        to="healthcare.patient",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthcare.medicalrecord",
                    ),
                ),
            ],
            options={
                "db_table": "access_permissions",
            },
        ),
    ]
