# Generated by Django 4.2.30 on 2026-05-12 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthcare", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="hospital_id",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
