# Generated by Django 4.2.30 on 2026-05-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthcare", "0002_alter_hospital_hospital_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="log_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
