# Generated by Django 4.2.30 on 2026-05-14 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZKProofRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proof_type",
                    models.CharField(
                        choices=[
                            ("zk_snark", "ZK-SNARK"),
                            ("zk_stark", "ZK-STARK"),
                            ("range", "Range Proof"),
                        ],
                        default="zk_snark",
                        max_length=20,
                    ),
                ),
                ("inputs", models.JSONField(default=list)),
                ("public_output", models.CharField(blank=True, max_length=500)),
                ("proof_payload", models.JSONField(default=dict)),
                ("generated_by", models.CharField(max_length=200)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "zk_proof_records",
                "ordering": ["-created_at"],
            },
        ),
    ]
